language: cpp
compiler: clang
before_script:
 - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip -O /tmp/gtest-1.7.0.zip
 - unzip /tmp/gtest-1.7.0.zip
 - GTEST_PATH=$PWD/gtest-1.7.0
 - export GTEST_PATH
 - cd gtest-1.7.0 && ./configure && make && cd ..

 - wget http://googlemock.googlecode.com/files/gmock-1.7.0.zip -O /tmp/gmock-1.7.0.zip
 - unzip /tmp/gmock-1.7.0.zip
 - GMOCK_PATH=$PWD/gmock-1.7.0
 - export GMOCK_PATH
 - cd gmock-1.7.0 && ./configure && make && cd ..
 
 - git clone https://github.com/FreeOpcUa/opcua-mappings.git
 - cd opcua-mappings && ./configure --with-gtest=$GTEST_PATH && make && cd ..

script: ./configure --with-gtest=$GTEST_PATH --with-gmock=$GMOCK_PATH --with-uamappings=$PWD/opcua-mappings && make && make check

